[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "hubspot.crm.object.contacts"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["HubSpot", "Customer", "Management", "Connector", "CRM"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.obj.contacts"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
